- name: Sync to S3
  run: >
    aws s3 sync
    ./docs
    s3://${{ secrets.DOC_AWS_S3_BUCKET }}/
    --acl public-read --follow-symlinks --delete

  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: 'eu-west-3'